### ISSUE TITLE
MTA api returning empty departure time causes a hard failure on pydantic validations

### ISSUE THREAD

**Issue by wilsonchaney** [nolanbconaway/underground#23]
👋 

After calling `SubwayFeed.get('L', api_key=API_KEY)`, I had the following error:

```
  File "/usr/local/lib/python3.9/site-packages/underground/models.py", line 201, in get
    return SubwayFeed(
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for SubwayFeed
entity -> 2 -> trip_update -> stop_time_update -> 0 -> departure -> time
  field required (type=value_error.missing)
entity -> 8 -> trip_update -> stop_time_update -> 0 -> departure -> time
  field required (type=value_error.missing)
  ```
  
  After some digging, I realized the feed dict being returned by the MTA included this:
  
  ```
                    {
                        "stop_sequence": 0,
                        "departure": {},
                        "stop_id": "L01N",
                        "schedule_relationship": 0
                    },
  ```

For clarity, a full copy of the dictionary is at https://gist.github.com/wilsonchaney/09b87a44206992a978bced1892ac24e3.

Basically, one of the elements of `stop_time_update` was malformed - it did not include a departure/arrival time and does not appear to be correct at all [1]

This is probably a bug on the MTA's part, but we should handle it more gracefully (maybe just drop this particular element of `stop_time_update`, judging by the data in the gist).
  
 [1] in this particular case, the train was halfway down its route, and had long since passed station `L01N`.

**Comment by nolanbconaway** [comment]
Fixed in #24
