### ISSUE TITLE
API key no longer required

### ISSUE THREAD

**Issue by WardBrian** [nolanbconaway/underground#36]
> Accounts and API keys are no longer required to access these feeds.

https://api.mta.info/#/

Could likely simplify some things

**Comment by nolanbconaway** [comment]
Well that's pleasant! Thanks for the heads up. I'll try to find some time to remove that logic from the library and cut a major release.

**Comment by WardBrian** [comment]
My use case for this has long periods of down time, so I usually have to rotate my keys before I start it up again. This time I noticed the old key still worked, and it is in fact because seemingly _any_ key works, as the MTA just ignores it now. 

So it's not strictly necessary to remove, but it is certainly easier to use if that isn't required

**Comment by nolanbconaway** [comment]
@WardBrian i rolled removal of the api key logic up with a bunch of dependency updates into a v1 release! (this thing hadn't been touched in over a year)

Thanks for letting me know about the MTAs policy change!

https://github.com/nolanbconaway/underground/releases/tag/v1.0.0
